
const translation = {
    "jobs" : "Jobs",
    "talants": "Talants",
    "contact" : "Contact us",
    "about" : "About us",
    // Company register side START
    "backToSignUp": "Back to sign up",
    "loading": "Loading...",
    "welcome": "Welcome",
    "companyRegisterTitle": "Complete your profile to join our global community of freelancers and start selling your services to our growing network of businesses.",
    "firstName": "Firstname*",
    "firstNameInput": "Write in your first name",
    "lastName": "Lastname*",
    "lastNameInput": "Write in your last name",
    "email": "E-mail*",
    "phoneNumber": "Phone Number*",
    "next": "Next",
    "back": "Back",
    "yourCompany": "Your company!",
    "addCompanyPhoto": "Add your company photo",
    "changeCompanyPhoto": "Change your company photo",
    "companyName": "Company name",
    "companyNameInput": "Name your company",
    "number": "Number",
    "companyPhoneNumberInput": "Company phone number",
    "aboutYourCompanyTitle": "About your company",
    "aboutYourCompanyDescription": "Write down some more information about your company",
    "location": "Location*",
    "locationInput": "Write a location",
    "locationDescriptionTitle": "Description",
    "locationDescriptionInput": "Write what your company do",
    "contactsCompany": "Contacts",
    "contactsCompanyInput": "Provide a link to your webSite",
    "contactsCompanyInput2": "Provide a link to your",
    "account": "account",
    "contactsCompanyDescription": "Choose in which of these social networks you have an account",
    // Company register side END
}

export default translation